#!/bin/bash

while read line
do
ipaddr=`echo $line | awk {'print $1'}`
passwd=`echo $line | awk {'print $2'}`


/usr/bin/expect<<EOF
set timeout 5

spawn ssh -l root $ipaddr 
expect {
      "*yes/n*" {               
                send "yes\r"
                expect "*assword:"
                send "$passwd\r"
                }
     "*assword:" {
                send "$passwd\r"
                }
     }
expect "*#*"
send "echo 'xxxxxxx_456' | passwd --stdin\r"
expect "*#*"
send "exit\r"
expect "*#*"
EOF

done<./xxxxx.txt
